<a href="https://colab.research.google.com/github/tobias-hoepfl/Digital-Organizations-SE/blob/main/assignments/assignment_6_Hoepfl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The following assignment consists again of a theoretical part (learning portfolio) and a practical part (assignment). The goal is to train a neural model from scratch, as we did a few weeks ago. I would like us to repeat the most important things so that we can consolidate our knowledge in this area, for this you will train a model on a dataset that I will provide via OLAT. 

The plan would be that in the first we will discuss your learnings from the theory part, that means you are relatively free to fill your Learning Portfolio on this topic and in the following week we will discuss your solutions of the Classification Model.

#Theory part (filling your Learning Portfolio, May 24)

In preparation for the practical part, I ask you to familiarize yourself with the following video sources in the next week:

1) Please watch the following video until random forests:

https://course.fast.ai/Lessons/lesson5.html

2) Please download the following notebooks and edit it in Google-Colab. Take notes and update your Learning Portfolio.

https://www.kaggle.com/code/jhoward/linear-model-and-neural-net-from-scratch

https://www.kaggle.com/code/jhoward/why-you-should-use-a-framework

The contents should be mostly known to you, because these contents are also based on chapter 4, which we have already worked on. We repeat the basics again with a new data set to consolidate our knowledge.



#Practical part (Assignment, May 31)

The following task is a binary classification task. The first column is our target. All variables are categorical variables from which you have to create dummy variables. The target column has only the property Q or F, which is to be modeled. As always, please create a train and a test data set, e.g. 80:20 or 90:10. Your goal is to create a neural network that best predicts the target column. Use probabilities with the sigmoid function as discussed in the theory. When designing your neural network, play with a few different numbers and sizes of layers and different activation functions.

To validate your model, you can compare your results with a logistic regression model. (Note: This data set should allow you to achieve very high accuracies: > 98% maybe even >99%) You can see how these results vary when you use 50% for testing and 50% for training.

When we have discussed the assignment, I will tell you what the data set is about, which has its origin from our nature.

In [5]:
import pandas as pd
from google.colab import drive
from google.colab import data_table
import matplotlib.pyplot as plt
data_table.enable_dataframe_formatter()

drive.mount('/content/drive')
df = pd.read_csv("/content/drive/MyDrive/DigitalOrganizations/data_homework_6.csv")

df.head(10)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


target variable_1 variable_2 variable_3 variable_4 variable_5 variable_6  \
0      Q          Y          T          O          U          Q          G   
1      F          Y          T          Z          U          B          G   
2      F          C          T          X          U          M          G   
3      Q          Y          Z          X          U          Q          G   
4      F          Y          T          H          G          O          G   
5      F          Y          Z          Z          U          B          G   
6      F          C          T          X          U          B          G   
7      F          C          Z          X          U          M          G   
8      Q          Y          Z          X          U          Q          G   
9      F          C          T          Z          U          B          G   

  variable_7 variable_8 variable_9  ... variable_13 variable_14 variable_15  \
0          D          O          L  ...           T           X           X   
1          D          C          L  ...           T           X           X   
2          D          C          O  ...           T           X           X   
3          D          O          O  ...           T           X           X   
4          X          C          L  ...           T           X           X   
5          D          C          O  ...           T           X           X   
6          D          C          H  ...           T           X           X   
7          D          C          O  ...           T           X           X   
8          D          O          Q  ...           T           X           X   
9          D          C          H  ...           T           X           X   

  variable_16 variable_17 variable_18 variable_19 variable_20 variable_21  \
0           Q           X           P           Q           L           T   
1           Q           X           P           Q           O           O   
2           Q           X           P           Q           O           O   
3           Q           X           P           Q           L           T   
4           Q           X           P           F           O           B   
5           Q           X           P           Q           L           O   
6           Q           X           P           Q           L           O   
7           Q           X           P           Q           O           T   
8           Q           X           P           Q           L           W   
9           Q           X           P           Q           L           T   

  variable_22  
0           V  
1           H  
2           N  
3           V  
4           H  
5           H  
6           N  
7           N  
8           H  
9           N  

[10 rows x 23 columns]

In [6]:
df.isna().sum()
#there are no na values which have to be removed

target         0
variable_1     0
variable_2     0
variable_3     0
variable_4     0
variable_5     0
variable_6     0
variable_7     0
variable_8     0
variable_9     0
variable_10    0
variable_11    0
variable_12    0
variable_13    0
variable_14    0
variable_15    0
variable_16    0
variable_17    0
variable_18    0
variable_19    0
variable_20    0
variable_21    0
variable_22    0
dtype: int64

In [7]:
import numpy as np
df.describe(include=(np.object))
#Look at some descriptive statistics for features which are all categorical

<ipython-input-7-7ac3a3c72751>:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df.describe(include=(np.object))


target variable_1 variable_2 variable_3 variable_4 variable_5  \
count    8124       8124       8124       8124       8124       8124   
unique      2          6          4         10          2          9   
top         F          Y          Z          O          G          O   
freq     4208       3656       3244       2284       4748       3528   

       variable_6 variable_7 variable_8 variable_9  ... variable_13  \
count        8124       8124       8124       8124  ...        8124   
unique          2          2          2         12  ...           4   
top             G          D          C          C  ...           T   
freq         7914       6812       5612       1728  ...        4936   

       variable_14 variable_15 variable_16 variable_17 variable_18  \
count         8124        8124        8124        8124        8124   
unique           9           9           1           4           3   
top              X           X           Q           X           P   
freq          4464        4384        8124        7924        7488   

       variable_19 variable_20 variable_21 variable_22  
count         8124        8124        8124        8124  
unique           5           9           6           7  
top              Q           X           W           E  
freq          3968        2388        4040        3148  

[4 rows x 23 columns]

In [8]:
#separate the target from the rest first
target = df['target']
df = df.drop(['target'], axis=1)

#one-hot-encoding using pandas directly
df = pd.get_dummies(df)
df.columns

Index(['variable_1_C', 'variable_1_D', 'variable_1_G', 'variable_1_L',
       'variable_1_T', 'variable_1_Y', 'variable_2_G', 'variable_2_H',
       'variable_2_T', 'variable_2_Z',
       ...
       'variable_21_T', 'variable_21_W', 'variable_21_Z', 'variable_22_E',
       'variable_22_H', 'variable_22_M', 'variable_22_N', 'variable_22_Q',
       'variable_22_V', 'variable_22_X'],
      dtype='object', length=117)

In [9]:
#now we really have a lot of columns
df.head()

variable_1_C  variable_1_D  variable_1_G  variable_1_L  variable_1_T  \
0             0             0             0             0             0   
1             0             0             0             0             0   
2             1             0             0             0             0   
3             0             0             0             0             0   
4             0             0             0             0             0   

   variable_1_Y  variable_2_G  variable_2_H  variable_2_T  variable_2_Z  ...  \
0             1             0             0             1             0  ...   
1             1             0             0             1             0  ...   
2             0             0             0             1             0  ...   
3             1             0             0             0             1  ...   
4             1             0             0             1             0  ...   

   variable_21_T  variable_21_W  variable_21_Z  variable_22_E  variable_22_H  \
0              1              0              0              0              0   
1              0              0              0              0              1   
2              0              0              0              0              0   
3              1              0              0              0              0   
4              0              0              0              0              1   

   variable_22_M  variable_22_N  variable_22_Q  variable_22_V  variable_22_X  
0              0              0              0              1              0  
1              0              0              0              0              0  
2              0              1              0              0              0  
3              0              0              0              1              0  
4              0              0              0              0              0  

[5 rows x 117 columns]

In [10]:
#change categories of target to numbers
target = target.astype('category').cat.codes

#because we have only two categories, now it is 0 and 1
target

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Length: 8124, dtype: int8

In [11]:
#change data format to tensor
import torch

#cast to float
df = df.astype(float)

#extract the feature columns and convert them to a tensor
t_indep = torch.tensor(df.values, dtype=torch.float)

#do the same for the label
t_dep = torch.tensor(target)

## Neural Network from scratch (see FastAI video and code)

For the neural network from scratch implementation I copied the relevant code parts and adapted them only minorly from https://www.kaggle.com/code/jhoward/linear-model-and-neural-net-from-scratch.

The comments were added by me which helped me to understand better what the code does - also compare my learning portfolio for that (bank churn)

In [12]:
from fastai.data.transforms import RandomSplitter

#Split the data in training and validation set (the alternative would be sklearn)
#In fastai this seems to return a list of indices
trn_split, val_split = RandomSplitter(seed=42)(df)

#the list of indices is now applied to the actual tensors (independent and dependent), so we get two tensors
trn_indep, val_indep = t_indep[trn_split], t_indep[val_split]
trn_dep, val_dep = t_dep[trn_split], t_dep[val_split]

#the default of fastai RandomSplitter seems to be 80/20 which can be seen when looking at the length
len(trn_indep), len(val_indep)

(6500, 1624)

In [34]:
#n_coeff is the number of features again (117 in our case)
n_coeff = t_indep.shape[1]

In [14]:
import torch.nn.functional as F

#calculates the predictions of the model
def calc_preds(coeffs, indeps):
    #coefficients are in this tuple shape which is initialized in the code further below
    l1,l2,const = coeffs
    #@ refers to matrix multiplication, then apply ReLU
    res = F.relu(indeps@l1)
    #for the output layer also add a bias
    res = res@l2 + const
    #apply sigmoid in the end, so the result is between 0 and 1
    return torch.sigmoid(res)

In [15]:
#calculates the loss which is the mean absolute error in our case
def calc_loss(coeffs, indeps, deps): return torch.abs(calc_preds(coeffs, indeps)-deps).mean()

In [16]:
def one_epoch(coeffs, lr):
    #in an epoch we first calculate the loss
    loss = calc_loss(coeffs, trn_indep, trn_dep)
    #then we calculate the gradients
    loss.backward()
    #We update the coefficients with the function defined before
    with torch.no_grad(): update_coeffs(coeffs, lr)
    #we print out the current loss
    print(f"{loss:.3f}", end="; ")

In [17]:
#for every feature we initialize a random weights and we do the same for the hidden layer
#we substract 0.5 in order to center them at 0

def init_coeffs(n_hidden=200):
    layer1 = (torch.rand(n_coeff, n_hidden)-0.5)/n_hidden
    layer2 = torch.rand(n_hidden, 1)-0.3
    #one bias for the output layer
    const = torch.rand(1)[0]
    #return as a tuple
    return layer1.requires_grad_(),layer2.requires_grad_(),const.requires_grad_()

In [18]:
def train_model(epochs=50, lr=100):
    #don't touch the seed for random number
    #I did this and the model could not fit anymore
    #as mentioned in the video, when doing this manually one has to be cautious about parameter initialization
    torch.manual_seed(442)
    #first initialize coefficients
    coeffs = init_coeffs()
    #then performe backpropagation for the number of epochs
    for i in range(epochs): one_epoch(coeffs, lr=lr)
    return coeffs

In [19]:
#Takes the coefficients at one point in time and updates them using the gradients and the learning rate
def update_coeffs(coeffs, lr):
    for layer in coeffs:
        #sub_ seems to be an internal function that directly subtracts something from the given tensor
        layer.sub_(layer.grad * lr)
        #resets the gradients
        layer.grad.zero_()

In [20]:
train
coeffs = train_model(lr=105.4)
#get stuck at a loss of 0.484
#I tried around with different learning rates and other parameters, but it did not change much

0.503; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 0.484; 

In [21]:
#Calculate the final accuracy in the validation set
def acc(coeffs): return (val_dep.bool()==(calc_preds(coeffs, val_indep)>0.5)).float().mean()
acc(coeffs)
#the accuracy is still very bad (gets stuck at a loss of 0.484) -> Why?

tensor(0.5277)

Does not work well. I gave up on this approach -> I suppose that one layer was enough in the Titanic case and for my bank churn learning portfolio task, but is not enough for the complex structure at this task.

Therefore: Try to add more layers using the approach using pytorch we had used earlier this semester already

## Approach using a framework

Compare the approach from the fastAI book chapter 4 (also used in a similar way for the iris dataset in my learning portfolio)

In [22]:
from fastai.tabular.all import *
set_seed(42)

In [28]:
trn_indep = trn_indep.to(torch.float32)
trn_dep = trn_dep.to(torch.float32)

In [29]:
#Create our model
torch.manual_seed(5)
simple_net = torch.nn.Sequential(
    torch.nn.Linear(117,20),
    torch.nn.ReLU(),
    torch.nn.Linear(20,1),
    #important! I did not do this in the beginning which caused problems because the predicted value was not always between 0 and 1
    torch.nn.Sigmoid()
)

#Uncomment for optional outputs
#print(list(simple_net.parameters()))
#initial predictions
#print('Initial predictions:')
#print(simple_net(x).flatten())

#learning rate
lr=0.05

#Create optimizer class
class BasicOptim:
    def __init__(self,params,lr): self.params,self.lr = list(params),lr

    def step(self, *args, **kwargs):
        for p in self.params: p.data -= p.grad.data * self.lr

    def zero_grad(self, *args, **kwargs):
        for p in self.params: p.grad = None

#Create instance of optimizer class
opt = BasicOptim(simple_net.parameters(), lr)

def calc_grad(xb, yb, model):
    preds = model(xb).flatten()
    loss = mse(preds, yb)
    global loss_value 
    loss_value = loss.item()
    loss.backward()

#Train
def train_epoch(model):
    calc_grad(trn_indep, trn_dep, model)
    opt.step()
    opt.zero_grad()

def train_model(model, epochs):
    for i in range(epochs):
        train_epoch(model)

train_model(simple_net, 3000)

#Output final loss
global loss_value
print(loss_value)

0.004331340081989765


In [32]:
#Performance metrics, but still on training data set

#if between 0 and 0.5 -> we predict 0
#if between 0.5 and 1 -> we predict 1

predictions = simple_net(trn_indep).flatten()
print('Predictions:')

print(predictions)
final_preds = torch.where(predictions < 0.5, 0, 1)

print('Final classification:')
print(final_preds)

print('True label y:')
print(trn_dep)

accuracy = torch.where(final_preds == trn_dep, 1., 0.).mean()
print('Accuracy:',accuracy)

#number of wrong predictions
wrongs = torch.where(final_preds == trn_dep, 0., 1.).sum()
print('Wrong instances:', wrongs)

#Accuracy is very high, but we are still on the training dataset

Predictions:
tensor([0.0691, 0.0183, 0.2097,  ..., 0.0471, 0.0207, 0.9971],
       grad_fn=<ReshapeAliasBackward0>)
Final classification:
tensor([0, 0, 0,  ..., 0, 0, 1])
True label y:
tensor([0., 0., 0.,  ..., 0., 0., 1.])
Accuracy: tensor(0.9980)
Wrong instances: tensor(13.)


In [33]:
#Now test on the validation dataset

#if between 0 and 0.5 -> we predict 0
#if between 0.5 and 1 -> we predict 1

predictions = simple_net(val_indep).flatten()
print('Predictions:')

print(predictions)
final_preds = torch.where(predictions < 0.5, 0, 1)

print('Final classification:')
print(final_preds)

print('True label y:')
print(val_dep)

accuracy = torch.where(final_preds == val_dep, 1., 0.).mean()
print('Accuracy:',accuracy)

#number of wrong predictions
wrongs = torch.where(final_preds == val_dep, 0., 1.).sum()
print('Wrong instances:', wrongs)

Predictions:
tensor([0.9964, 0.0135, 0.0223,  ..., 0.0025, 0.0219, 0.0039],
       grad_fn=<ReshapeAliasBackward0>)
Final classification:
tensor([1, 0, 0,  ..., 0, 0, 0])
True label y:
tensor([1, 0, 0,  ..., 0, 0, 0], dtype=torch.int8)
Accuracy: tensor(0.9982)
Wrong instances: tensor(3.)


Accuracy on the validation set is 99.82 percent which very good!