<a href="https://colab.research.google.com/github/tobias-hoepfl/Digital-Organizations-SE/blob/main/assignments/assignment_3_Hoepfl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#hide
! [ -e /content ] && pip install -Uqq fastbook
import fastbook
from fastai.vision.all import *
from fastbook import *
fastbook.setup_book()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.8/719.8 kB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 34.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.7/468.7 kB 16.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 57.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 kB 7.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 20.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 50.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 3.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 kB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Introduction to Artificial Neural Networks

Please read the introdcution of neuronal networks of the book *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow*, p. 299-316.

Why have neural networks, even though they were invented early on, only now caught on?

<b>Answer:</b>

- Larger amounts of data available than before: this has enabled neural networks to outperform other machine learning techniques for complex problems.
- Increased computing power: thanks to Moore's Law and the gaming industry, it is now possible to train large neural networks in a reasonable amount of time. Cloud platforms have made this power accessible to everyone.
- Improvements in training algorithms have had a huge impact on ANNs
- Theoretical limitations of ANNs, such as local optima, have proven to be less problematic in practice, particularly for larger neural networks.
- ANNs are in a virtuous circle of funding and progress: amazing products based on them regularly make headline news (e.g. ChatGPT), attract more attention and funding, which results in further progress and even better products.

<br>

What is a percepton and a threshold logic unit (TLU)? Try to define a linear function and a step function of your choice, use some values of your choice and explain what might be the result of the percepton. (maybe using max. two TLU's)

<b>Answer:</b>

TLU:
- Threshold logic unit
- It takes one or more inputs and produces a single output by taking the weighted sum of its inputs and passing it through a step function.
- The step function can be a heaviside function or a sign function for example.
- Can be used as a simple binary classifier

<br>


Perceptron:
- A perceptron is a simple type of neural network unit invented by Frank Rosenblatt in 1957.
- Composed of multiple TLUs organized in a single layer (called the output layer). Every TLU is connected to the input layer.
- The perceptron can be trained using an algorithm called the perceptron learning rule (see book). The rule works as follows: When an output neuron produces an incorrect prediction, the connection weights from the inputs that would have led to the correct prediction are strengthened. This means that the perceptron learning rule adjusts the weights of the inputs based on the difference between the actual output and the desired output, in order to minimize the error.


<br>

Example for Perceptron (consisting of two TLUs):

- Two inputs: x<sub>1</sub> and x<sub>2</sub>
- Two TLUs with different linear functions z<sub>1</sub> and z<sub>2</sub>:
  - z<sub>1</sub> = 2x<sub>1</sub> - x<sub>2</sub> + 3
  - z<sub>2</sub> = x<sub>1</sub> - x<sub>2</sub> - 10

- Both have a heavide step function (see the formula in the book)
- Example values:
  - x<sub>1</sub> = 2 and x<sub>2</sub> = 2 
   - -> z<sub>1</sub> = 5 -> heaviside(z<sub>1</sub>) = 1
   - -> z<sub>2</sub> = -14 -> heaviside(z<sub>2</sub>) = 0
  - x<sub>1</sub> = 50 and x<sub>2</sub> = 0 
   - -> z<sub>1</sub> = 103 -> heaviside(z<sub>1</sub>) = 1
   - -> z<sub>2</sub> = 40 -> heaviside(z<sub>2</sub>) = 1



<br>

What is a fully connected layer and a output layer?

<b>Answer:</b>
- Fully connected layer: every TLU is connected to every input (=dense layer)
- Output layer: Layer that produces the final output (in case there is only one layer, this is also the output layer)

<br>

Why can we easily combine the equations of multiple instances into a fully connected layer?

<b>Answer:</b>
Because linear algebra allows to work with vectors and matrices. This way we can do forward/backward propagation for many instances at the same time.

<br>

What problem did Marvin Minsky and Seymour Paper highlight that perceptrons could not solve? What is a possible solution?

<b>Answer:</b>

They noted that perceptrons are unable to solve specific problems. This can also be the case for simple problems, e.g. the XOR-problem (see the graph in the book). Stacking multiple perceptrons, i.e. adding another layer, makes it possible to solve some of these problems.

<br>

What is a deep neuronal network? What are hidden layers? What means feedforward neural network (FNN).

<b>Answer:</b>
- Hidden layers are additional layers that are not output layers. A neural network can consist of many of these.
- A neural network that contains a lot of hidden layers is called a deep neural network (although the exact number depends on the definition)
- FNN: If the signal flows only in one direction from input layer to output layer

<br>

Try to explain how backpropagation works! (In Addition, you can have a look to the following example, which tries manually to compute the backprogation of a simple linear network. https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/ OR you can also read through the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy))


<b>Answer:</b>

- Backpropagation handles a small chunk of the training data at a time, and repeats this process multiple times on the entire training set.
- The input data is fed into the input layer of the network. Then, the network calculates the output of the neurons in each hidden layer, continuing until the output layer is reached. This forward pass keeps all the intermediate calculations.
- The network's output error is measured using a loss function.
- The algorithm figures out how much each output bias and connection to the output layer contributed to the error, then works backward through each layer until it gets to the input layer.
- The backward pass efficiently measures the error gradient across all the connection weights and biases in the network by propagating the error gradient backward through the network.
- Lastly, the algorithm uses the error gradients to adjust all the connection weights in the network through a process called gradient descent.

<br>

Why do we need activation functions, wouldn't it be easier just using linear functions?

<b>Answer:</b>

When chaining multiple linear functions, one always ends up with a linear function again. But many complex problems cannot be solved using linear functions. On the other hand, Artificial Neural Networks using non-linear activation functions make it possible to express any continuous function.

<br>


## Ideas for the learning portfolio: 

1) For example, you could train a single TLU to classify iris flowers based on petal length and width in the !!!pyTorch!! environment.

2) You could add to our king county housepricing ML project a neuronal network and compare it to the other models. 

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

# A traditional approach: training a digit classifier and learning pyTorch tensors.

For this assignment, I ask you to read the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy) to the beginning of the chapter *Stochastic Gradient Descent (SGD)*. 

First, try to summarize what we know about pyTorch tensors by trying to predict whether we have a 1 or a 7 in the MNIST dataset using a traditional rule-based programming approach. Therefore use pyTorch tensors for the entire tasks and fulfill the following steps:

1) Randomly split the MNIST dataset (1 and 7) into a training dataset and a test dataset in a ratio of 80:20.

2) Instead of using an optimal 1 or 7 with the mean over the training dataset, try to calculate the sum of the distances to all instances in the training set for each instance in the test dataset. You can use the L2 norm. 

3) For each instance in the test set, decide if it is a 1 or 7 and calculate the precision.

Do we get a similar good result?


In [ ]:
#FastAI MNIST_SAMPLE does only have 3s and 7s available, so the full MNIST (or alternatively MNIST) dataset needs to be loaded (which has a path structure that is a bit different)
path = untar_data(URLs.MNIST)

In [ ]:
Path.BASE_PATH = path

In [ ]:
path.ls()

(#2) [Path('testing'),Path('training')]

In [ ]:
# The subtask "Randomly split the MNIST dataset (1 and 7) into a training dataset and a test dataset in a ratio of 80:20" not entirely clear.
# Splitting in training and test data has already been done, so in my opinion it does not make sense to split the test data again

In [ ]:
# Get fastAI lists for ones and sevens
ones = (path/'training'/'1').ls().sorted()
sevens = (path/'training'/'7').ls().sorted()

In [ ]:
#only 1000 elements are taken to make code faster
ones = ones[0:999]
sevens = sevens[0:999]

In [ ]:
#look at image of the first one in the dataset
im1_path = ones[1]
im1 = Image.open(im1_path)
im1

In [ ]:
#Create tensors for ones and sevens and stack them, to have a tensor for each label instead of a list of tensors
one_tensors = [tensor(Image.open(o)) for o in ones]
seven_tensors = [tensor(Image.open(o)) for o in sevens]

stacked_ones = torch.stack(one_tensors).float()/255
stacked_sevens = torch.stack(seven_tensors).float()/255

#Check the resulting shape
stacked_sevens.shape

torch.Size([999, 28, 28])

In [ ]:
#Also transform test data, so they have the same data type and shape
ones_testing = (path/'testing'/'1').ls().sorted()
sevens_testing = (path/'testing'/'7').ls().sorted()

one_tensors_testing = [tensor(Image.open(o)) for o in ones_testing]
seven_tensors_testing = [tensor(Image.open(o)) for o in sevens_testing]

#only take 200 elements to make code faster
stacked_ones_testing = (torch.stack(one_tensors_testing).float()/255)[0:199]
stacked_sevens_testing = (torch.stack(seven_tensors_testing).float()/255)[0:199]

In [ ]:
#Algorithm: First only on one instance of 1

inst_1 = stacked_ones[1]
inst_2 = stacked_ones[2]

#Calculate l2-distance between two instances
F.mse_loss(inst_1, inst_2).sqrt()
print(F.mse_loss(inst_1, inst_2).sqrt())

tensor(0.2643)


In [ ]:
#Calculate sum of the l2-distance to all other instances that are ones in the data set
#Using list comprehensions
def sum_of_distances(instance, training_tensor):
  list_distances = [(F.mse_loss(instance, t).sqrt()).item() for t in training_tensor]
  sum_distances = sum(list_distances)
  return sum_distances

print(sum_of_distances(inst_2, stacked_ones))
print(sum_of_distances(inst_2, stacked_sevens))

#as expected: is higher for ones than for sevens (correct classification for this instance)

236.24830117821693
315.3656358718872


In [ ]:
#sum_of_distances: broadcasting does not seem to work if both arguments are tensors (would be the case in sum_of_distances), so a loop has to be written -> Is there a more efficient way using tensors directly?
def distances(instances):
  distances_to_ones = [sum_of_distances(instance, stacked_ones) for instance in instances]
  distances_to_sevens = [sum_of_distances(instance, stacked_sevens) for instance in instances]
  return tensor(distances_to_ones), tensor(distances_to_sevens)

In [ ]:
distances_of_ones = distances(stacked_ones_testing)
distances_of_sevens = distances(stacked_sevens_testing)

In [ ]:
distances_of_ones_to_ones, distances_of_ones_to_sevens = distances_of_ones
distances_of_sevens_to_ones, distances_of_sevens_to_sevens = distances_of_sevens

predict_ones_correctly = distances_of_ones_to_ones < distances_of_ones_to_sevens
predict_sevens_correctly = distances_of_sevens_to_sevens < distances_of_sevens_to_ones
#accuracy for ones
print(predict_ones_correctly.float().mean())

#accuracy for sevens
print(predict_sevens_correctly.float().mean())

tensor(1.)
tensor(0.7035)


Observations:

- Accuracy for ones (100%) is higher than for sevens (70%) in the test set used
- Further investigation should be made why there is such a discrepancy
- Algorithm is much more runtime-intense (because the distance to all other instances has to be calculated) -> therefore only a subset of the data was taken
- 1 vs. 7 as compared to 3 vs. 7 (in the example).
- So it is difficult to directly compare the two algorithms

# Stochastic Gradient Descent (SGD)

For this exercise I ask you to read the chapter Stochastic Gradient Descent (SGD) from the Google Colab 04_mnist_basics.ipynb in paralell. The chapter starts with a single TLU, compare p. 304 in "Hands on Machine Learning". Go through all 7 steps which are an easy example of how Stochastic Gradient Descent works.

Our goal is to train a single TLU, which can decide if one number is larger then the other one. Therefore we create 100 random pairs with pyTorch and create a target vector which is eather 1 or 0.


In [ ]:
x = torch.randn((100, 2))
y = torch.where(x[:,0] > x[:,1], 1.0, 0.0)
print(x)
print(y)

tensor([[ 1.9269e+00,  1.4873e+00],
        [ 9.0072e-01, -2.1055e+00],
        [ 6.7842e-01, -1.2345e+00],
        [-4.3067e-02, -1.6047e+00],
        [-7.5214e-01,  1.6487e+00],
        [-3.9248e-01, -1.4036e+00],
        [-7.2788e-01, -5.5943e-01],
        [-7.6884e-01,  7.6245e-01],
        [ 1.6423e+00, -1.5960e-01],
        [-4.9740e-01,  4.3959e-01],
        [-7.5813e-01,  1.0783e+00],
        [ 8.0080e-01,  1.6806e+00],
        [ 1.2791e+00,  1.2964e+00],
        [ 6.1047e-01,  1.3347e+00],
        [-2.3162e-01,  4.1759e-02],
        [-2.5158e-01,  8.5986e-01],
        [-1.3847e+00, -8.7124e-01],
        [-2.2337e-01,  1.7174e+00],
        [ 3.1888e-01, -4.2452e-01],
        [ 3.0572e-01, -7.7459e-01],
        [-1.5576e+00,  9.9564e-01],
        [-8.7979e-01, -6.0114e-01],
        [-1.2742e+00,  2.1228e+00],
        [-1.2347e+00, -4.8791e-01],
        [-9.1382e-01, -6.5814e-01],
        [ 7.8024e-02,  5.2581e-01],
        [-4.8799e-01,  1.1914e+00],
        [-8.1401e-01, -7.359

Your task is to create a function f that is a single TLU, meaning that it summarizes x with weights a, b, c:

$ax_0+bx_1+c$

In Addition we are using a *sigmoid()* function as step function.

$f = \text{sigmoid}(ax_0+bx_1+c)$

In [ ]:
def f(x, params):
    a,b,c = params
    return 1/(1+torch.exp(a*x[:,0] + b*x[:,1] + c))

print(f(x, [3,-2,1]))

tensor([2.1749e-02, 3.6575e-04, 4.0526e-03, 1.6624e-02, 9.8958e-01, 6.7246e-02, 5.1619e-01, 9.4435e-01, 1.9342e-03, 7.9760e-01, 9.6866e-01, 4.8971e-01, 9.5823e-02, 4.5961e-01, 4.4482e-01, 8.1373e-01,
        8.0401e-01, 9.5709e-01, 5.7018e-02, 3.0285e-02, 9.9654e-01, 6.0756e-01, 9.9915e-01, 8.4917e-01, 6.0473e-01, 4.5451e-01, 9.4515e-01, 4.9251e-01, 9.6380e-01, 6.3220e-01, 9.5178e-01, 9.9513e-01,
        2.6019e-02, 1.3478e-03, 8.0572e-02, 9.9116e-01, 6.3741e-01, 4.2134e-01, 1.7837e-02, 9.8398e-01, 1.5315e-01, 8.6428e-01, 1.7374e-01, 1.3121e-02, 1.4847e-02, 9.6631e-01, 9.2493e-01, 1.7344e-02,
        9.9945e-01, 3.5693e-02, 1.4732e-01, 6.0533e-03, 7.4294e-01, 1.3501e-01, 6.7953e-01, 1.6752e-01, 9.5955e-01, 8.5215e-01, 4.7597e-02, 7.7260e-01, 3.8219e-01, 5.3267e-01, 2.6461e-02, 8.8098e-02,
        8.4111e-03, 7.4068e-01, 9.3577e-01, 1.4037e-01, 1.2280e-02, 9.9811e-01, 8.9955e-01, 9.1162e-01, 9.7885e-01, 4.9436e-02, 9.7159e-02, 8.0329e-01, 4.7226e-01, 9.7357e-01, 9.9634e-01, 9.8539e-01,


In addition to our TLU function, we need a loss function. Your task is to implement a absolute difference loss function, $∑|x_i-y_i|$, which counts the number of wrong guesses.

In [ ]:
def mae(preds, targets): return (abs(preds-targets)).mean()

Try to train your single TLU with the absolute difference loss function, use the following code. Choose an appropriate step weight `lr` and try to explain what is happing in each line.

**Answer:** 

Explanation see comments in code

In [ ]:
#lr is chosen smaller (see fastAI) -> Combined with more iterations it provides good results (see next code chunk)
lr = 0.5

#parameters are initialized randomly
params = torch.randn(3).requires_grad_()

def apply_step(params, prn=True):
    #calculate predictions
    preds = f(x, params)
    #calculate loss with function defined before
    loss = mae(preds, y)
    #calculate gradient
    loss.backward()
    #parameters are updated using the learning rate and the gradient
    params.data -= lr * params.grad.data
    params.grad = None
    #Print parameters and current loss
    if prn: print(params);print(loss.item())
    return preds

#We apply it 100 times (to account for smaller learning rate)
for i in range(100): apply_step(params)

tensor([-0.5397,  1.6738,  0.0187], requires_grad=True)
0.3251832127571106
tensor([-0.6037,  1.6825,  0.0261], requires_grad=True)
0.31654122471809387
tensor([-0.6668,  1.6903,  0.0329], requires_grad=True)
0.30815181136131287
tensor([-0.7291,  1.6972,  0.0394], requires_grad=True)
0.3000248968601227
tensor([-0.7903,  1.7034,  0.0454], requires_grad=True)
0.2921690046787262
tensor([-0.8505,  1.7090,  0.0511], requires_grad=True)
0.28459101915359497
tensor([-0.9095,  1.7140,  0.0564], requires_grad=True)
0.2772960662841797
tensor([-0.9674,  1.7186,  0.0614], requires_grad=True)
0.2702873945236206
tensor([-1.0241,  1.7227,  0.0661], requires_grad=True)
0.26356640458106995
tensor([-1.0795,  1.7266,  0.0705], requires_grad=True)
0.2571326196193695
tensor([-1.1337,  1.7303,  0.0746], requires_grad=True)
0.2509838938713074
tensor([-1.1867,  1.7338,  0.0784], requires_grad=True)
0.24511656165122986
tensor([-1.2383,  1.7373,  0.0820], requires_grad=True)
0.23952539265155792
tensor([-1.2887,  1

Write a line of code that counts the number of wrong predictions, rounding your predictions with *round()*.

In [ ]:
preds = f(x, params)

#0 means no difference (i.e. correct prediction)
diff = preds.round()-y

#transform to list to count occurences
print(diff.tolist().count(0))
print(diff.tolist().count(-1) + diff.tolist().count(1))

#99% correct predictions!

99
1
